name: Generate SBOM

on:
  workflow_dispatch:

jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX SBOM generator
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json
