name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    name: Generate SBOM in CycloneDX JSON format

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CycloneDX Node module
        run: npm install -g @cyclonedx/bom

      - name: Install dependencies
        run: npm ci

      - name: Generate SBOM
        run: cyclonedx-bom --output-format json --output-file sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: juice-shop-sbom
          path: sbom.json
