name: Generate and Upload SBOM

on:
  push:
    branches:
      - master

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SBOM (voorbeeld command)
        run: |
          echo '{"bomFormat": "CycloneDX"}' > sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
